# -*- coding: utf-8 -*-
"""mmo_лр5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEJKL9oUnLjgu9YYlXL11_BLX6ACKrH4
"""

# -*- coding: utf-8 -*-
"""
Лабораторная работа: Реализация алгоритма Policy Iteration
Среда: CliffWalking-v1
"""

!pip install gymnasium matplotlib seaborn -q

import numpy as np
import gymnasium as gym
import matplotlib.pyplot as plt
from IPython.display import clear_output, display
import matplotlib.patches as patches
from collections import defaultdict
import time
import warnings
import os
warnings.filterwarnings('ignore')

# ==================== 环境参数 ====================
HEIGHT = 4
WIDTH = 12
START_POS = 36          # (3,0) 默认起始位置
GOAL_POS = (3, 11)      # (3,11) 默认目标
GOAL_STATE = 47         # 3*12+11
CLIFF_STATES = [3 * WIDTH + j for j in range(1, WIDTH - 1)]  # 37-46
# 创建保存图片的文件夹
os.makedirs('policy_iteration_results', exist_ok=True)

def get_env_info(env):
    return {
        'height': HEIGHT, 'width': WIDTH,
        'start_pos': START_POS, 'goal_pos': GOAL_POS,
        'goal_state': GOAL_STATE, 'cliff_states': CLIFF_STATES
    }

def render_cliffworld(V=None, policy=None, title="", figsize=(12, 4)):
    """Визуализация среды с функцией ценности и стратегией"""
    height, width = HEIGHT, WIDTH
    start_pos = START_POS
    goal_pos = GOAL_POS
    cliff_states = CLIFF_STATES

    fig, ax = plt.subplots(figsize=figsize)

    # Тепловая карта для функции ценности
    grid = np.zeros((height, width))
    if V is not None:
        for i in range(height):
            for j in range(width):
                s = i * width + j
                if s < len(V):
                    grid[i, j] = V[s]

    im = ax.imshow(grid, cmap='YlOrRd', interpolation='nearest')
    plt.colorbar(im, ax=ax, label='V(s)')

    ax.set_xticks(np.arange(width))
    ax.set_yticks(np.arange(height))
    ax.set_xticklabels(np.arange(width))
    ax.set_yticklabels(np.arange(height))
    ax.grid(True, color='black', linewidth=0.5)

    # Старт S
    start_i, start_j = start_pos // width, start_pos % width
    rect = patches.Rectangle((start_j - 0.5, start_i - 0.5), 1, 1,
                              linewidth=2, edgecolor='green', facecolor='none', linestyle='--')
    ax.add_patch(rect)
    ax.text(start_j, start_i, 'S', ha='center', va='center', fontsize=12, fontweight='bold', color='green')

    # Цель G
    goal_i, goal_j = goal_pos
    rect = patches.Rectangle((goal_j - 0.5, goal_i - 0.5), 1, 1,
                              linewidth=2, edgecolor='gold', facecolor='none')
    ax.add_patch(rect)
    ax.text(goal_j, goal_i, 'G', ha='center', va='center', fontsize=12, fontweight='bold', color='gold')

    # Обрыв X
    for s in cliff_states:
        i, j = s // width, s % width
        ax.text(j, i, 'X', ha='center', va='center', fontsize=14, fontweight='bold', color='red')
        rect = patches.Rectangle((j - 0.5, i - 0.5), 1, 1, facecolor='darkred', alpha=0.3)
        ax.add_patch(rect)

    # Стратегия (стрелки)
    if policy is not None:
        action_symbols = {0: '↑', 1: '→', 2: '↓', 3: '←'}
        for i in range(height):
            for j in range(width):
                s = i * width + j
                if s in cliff_states or s == start_pos or s == GOAL_STATE:
                    continue
                if s < len(policy):
                    symbol = action_symbols.get(policy[s], '?')
                    ax.text(j, i, symbol, ha='center', va='center', fontsize=16,
                           fontweight='bold', color='darkblue',
                           bbox=dict(boxstyle="circle,pad=0.2", facecolor='white', alpha=0.7))

    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.set_xlabel('Колонка')
    ax.set_ylabel('Строка')
    plt.tight_layout()
    return fig

def render_test(state, step, total_reward, figsize=(12, 4)):
    """Визуализация тестирования (без тепловой карты)"""
    height, width = HEIGHT, WIDTH
    start_pos = START_POS
    goal_pos = GOAL_POS
    cliff_states = CLIFF_STATES

    fig, ax = plt.subplots(figsize=figsize)

    # Фон
    grid_display = np.zeros((height, width))
    ax.imshow(grid_display, cmap='Greys', interpolation='nearest', alpha=0.3)

    # Старт S
    start_i, start_j = start_pos // width, start_pos % width
    rect = patches.Rectangle((start_j - 0.5, start_i - 0.5), 1, 1, facecolor='lightgreen', alpha=0.5)
    ax.add_patch(rect)
    ax.text(start_j, start_i, 'S', ha='center', va='center', fontsize=14, fontweight='bold')

    # Цель G
    goal_i, goal_j = goal_pos
    rect = patches.Rectangle((goal_j - 0.5, goal_i - 0.5), 1, 1, facecolor='gold', alpha=0.5)
    ax.add_patch(rect)
    ax.text(goal_j, goal_i, 'G', ha='center', va='center', fontsize=14, fontweight='bold')

    # Обрыв X
    for s in cliff_states:
        i, j = s // width, s % width
        rect = patches.Rectangle((j - 0.5, i - 0.5), 1, 1, facecolor='darkred', alpha=0.5)
        ax.add_patch(rect)
        ax.text(j, i, 'X', ha='center', va='center', fontsize=12, color='white', fontweight='bold')

    # Агент A
    current_i, current_j = state // width, state % width
    circle = patches.Circle((current_j, current_i), 0.3, facecolor='blue', edgecolor='white', linewidth=2)
    ax.add_patch(circle)
    ax.text(current_j, current_i, 'A', ha='center', va='center', fontsize=10, color='white', fontweight='bold')

    ax.set_xticks(np.arange(width))
    ax.set_yticks(np.arange(height))
    ax.set_xticklabels(np.arange(width))
    ax.set_yticklabels(np.arange(height))
    ax.grid(True, color='black', linewidth=0.5)
    ax.set_title(f'Тестирование - Шаг {step} | Награда: {total_reward:.1f}')

    plt.tight_layout()
    return fig

def policy_evaluation(env, policy, gamma=0.99, theta=1e-6):
    """Оценивание стратегии"""
    nS = env.observation_space.n
    V = np.zeros(nS)
    while True:
        delta = 0
        for s in range(nS):
            v = V[s]
            a = policy[s]
            new_v = 0
            for prob, next_state, reward, terminated in env.unwrapped.P[s][a]:
                new_v += prob * (reward + gamma * V[next_state] * (not terminated))
            V[s] = new_v
            delta = max(delta, abs(v - V[s]))
        if delta < theta:
            break
    return V

def policy_improvement(env, V, gamma=0.99):
    """Улучшение стратегии"""
    nS, nA = env.observation_space.n, env.action_space.n
    new_policy = np.zeros(nS, dtype=int)
    for s in range(nS):
        q_values = np.zeros(nA)
        for a in range(nA):
            q_val = 0
            for prob, next_state, reward, terminated in env.unwrapped.P[s][a]:
                q_val += prob * (reward + gamma * V[next_state] * (not terminated))
            q_values[a] = q_val
        new_policy[s] = int(np.argmax(q_values))
    return new_policy

def policy_iteration(env, gamma=0.99, theta=1e-6, max_iterations=20):
    """Алгоритм итерации по стратегиям"""
    nS, nA = env.observation_space.n, env.action_space.n
    policy = np.random.randint(0, nA, size=nS)
    history_V, history_policies = [], []

    print("=" * 70)
    print("ЗАПУСК АЛГОРИТМА POLICY ITERATION")
    print("=" * 70)

    for iteration in range(max_iterations):
        print(f"\n--- Итерация {iteration + 1} ---")
        V = policy_evaluation(env, policy, gamma, theta)
        new_policy = policy_improvement(env, V, gamma)

        history_V.append(V.copy())
        history_policies.append(policy.copy())

        if np.array_equal(policy, new_policy):
            print(f"\n✅ АЛГОРИТМ СОШЁЛСЯ НА ИТЕРАЦИИ {iteration + 1}")
            return new_policy, V, history_V, history_policies
        policy = new_policy

    print(f"\n⚠️ Достигнуто максимальное число итераций ({max_iterations})")
    return policy, V, history_V, history_policies

def create_convergence_plot(history_values, history_policies):
    """График сходимости"""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    ax1 = axes[0]
    iterations = range(1, len(history_values) + 1)
    n_states = len(history_values[0])
    sample_states = np.random.choice(n_states, size=min(5, n_states), replace=False)
    for state in sample_states:
        values = [V[state] for V in history_values]
        ax1.plot(iterations, values, 'o-', label=f'Состояние {state}', linewidth=2)
    ax1.set_xlabel('Итерация')
    ax1.set_ylabel('V(s)')
    ax1.set_title('Сходимость функции ценности')
    ax1.legend()
    ax1.grid(True)

    ax2 = axes[1]
    policy_changes = []
    prev_policy = None
    for i, policy in enumerate(history_policies):
        changes = len(policy) if i == 0 else np.sum(prev_policy != policy)
        policy_changes.append(int(changes))
        prev_policy = policy
    ax2.bar(iterations[:len(policy_changes)], policy_changes, color='steelblue', alpha=0.7)
    ax2.set_xlabel('Итерация')
    ax2.set_ylabel('Изменённые действия')
    ax2.set_title('Сходимость стратегии')
    ax2.grid(True, alpha=0.3, axis='y')

    plt.suptitle('Анализ сходимости Policy Iteration', fontsize=14, fontweight='bold')
    plt.tight_layout()
    return fig

def test_policy(env, policy, episodes=2, delay=0.5):
    """Тестирование обученной стратегии"""
    print("\n" + "=" * 70)
    print("ТЕСТИРОВАНИЕ ОБУЧЕННОЙ СТРАТЕГИИ")
    print("=" * 70)
    print(f"Старт: (0,0) | Цель: ({GOAL_POS[0]},{GOAL_POS[1]})")

    action_symbols = {0: '↑', 1: '→', 2: '↓', 3: '←'}
    height, width = HEIGHT, WIDTH
    start_pos = START_POS
    cliff_states = CLIFF_STATES

    for ep in range(episodes):
        state, _ = env.reset()
        total_reward = 0
        steps = 0
        done = False
        truncated = False

        print(f"\n{'='*40}")
        print(f"Эпизод {ep + 1}")
        print(f"{'='*40}")

        while not (done or truncated) and steps < 100:
            # 显示当前状态（不清屏，所有图都会保留）
            fig = render_test(state, steps, total_reward)
            plt.show()

            action = policy[state]
            current_i, current_j = state // width, state % width
            print(f"\nСостояние: {state} (строка {current_i}, колонка {current_j})")
            print(f"Действие: {action_symbols.get(action, '?')}")

            next_state, reward, done, truncated, _ = env.step(action)
            total_reward += reward
            steps += 1
            state = next_state

            print(f"Награда: {reward:.1f}")

            if state == GOAL_STATE:
                # 目标到达后，再显示一帧确认
                fig = render_test(state, steps, total_reward)
                plt.title(f'🏁 ДОСТИГНУТА ЦЕЛЬ! 🏁')
                plt.show()
                print("🏁 ДОСТИГНУТА ЦЕЛЬ! 🏁")
                done = True
            elif state in cliff_states:
                print("💀 УПАЛ В ОБРЫВ! 💀")
                done = True

            time.sleep(delay)
            plt.close(fig)

        print(f"\n📊 Результат эпизода {ep+1}: шагов={steps}, награда={total_reward:.1f}")
        print("\n" + "-" * 40)

def main():
    print("=" * 70)
    print("ЛАБОРАТОРНАЯ РАБОТА: Реализация алгоритма Policy Iteration")
    print("=" * 70)
    print(f"\nПараметры среды CliffWalking-v1:")
    print(f"  Размер: {HEIGHT}x{WIDTH}")
    print(f"  Старт S: состояние {START_POS} (строка 0, колонка 0)")
    print(f"  Цель G: состояние {GOAL_STATE} (строка {GOAL_POS[0]}, колонка {GOAL_POS[1]})")
    print(f"  Обрыв X: состояния {CLIFF_STATES[0]}-{CLIFF_STATES[-1]} (строка 3, колонки 1-10)")
    print(f"\nПравила:")
    print(f"  - Награда за шаг: -1")
    print(f"  - Падение в обрыв: -100 (возврат на старт)")
    print(f"  - Достижение цели: 0 (эпизод завершается)")

    # Создание среды
    env = gym.make('CliffWalking-v1')
    print(f"\nПространство состояний: {env.observation_space.n}")
    print(f"Пространство действий: {env.action_space.n}")

    # Запуск алгоритма
    optimal_policy, optimal_V, history_V, history_policies = policy_iteration(env)

    # Количество итераций
    print(f"\n{'='*70}")
    print(f"РЕЗУЛЬТАТЫ ОБУЧЕНИЯ")
    print(f"{'='*70}")
    print(f"Количество итераций до сходимости: {len(history_policies)}")

    # Финальная визуализация (с тепловой картой)
    print(f"\n--- ФИНАЛЬНАЯ ОПТИМАЛЬНАЯ СТРАТЕГИЯ ---")
    final_fig = render_cliffworld(optimal_V, optimal_policy, "Оптимальная стратегия π*(s) и функция ценности V*(s)")
    final_fig.savefig('policy_iteration_results/final_optimal_policy.png', dpi=150, bbox_inches='tight')
    plt.show()
    plt.close(final_fig)

    # График сходимости
    print(f"\n--- ГРАФИК СХОДИМОСТИ ---")
    conv_fig = create_convergence_plot(history_V, history_policies)
    conv_fig.savefig('policy_iteration_results/convergence_plot.png', dpi=150, bbox_inches='tight')
    plt.show()
    plt.close(conv_fig)

    # Статистика оптимальной функции ценности
    print(f"\nСтатистика оптимальной функции ценности V*(s):")
    print(f"  Минимальное значение: {optimal_V.min():.2f}")
    print(f"  Максимальное значение: {optimal_V.max():.2f}")
    print(f"  Среднее значение: {optimal_V.mean():.2f}")

    # Распределение действий
    action_counts = defaultdict(int)
    for a in optimal_policy:
        action_counts[a] += 1
    action_names = {0: 'ВВЕРХ (↑)', 1: 'ВПРАВО (→)', 2: 'ВНИЗ (↓)', 3: 'ВЛЕВО (←)'}
    print(f"\nРаспределение действий в оптимальной стратегии:")
    for a, count in action_counts.items():
        print(f"  {action_names.get(a, str(a))}: {count} из {len(optimal_policy)} ({100*count/len(optimal_policy):.1f}%)")

    # Тестирование
    test_policy(env, optimal_policy, episodes=2, delay=0.5)

    print(f"\n📁 Все рисунки сохранены в папку: policy_iteration_results/")
    env.close()

if __name__ == "__main__":
    main()