# -*- coding: utf-8 -*-
"""MMO-лр3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pshNOXb7qDUiZpNlGJHu8zBy-hNElsu
"""

# -*- coding: utf-8 -*-
"""
Лабораторная работа 3 - Методы многомерной оптимизации
Функция Розенброка: f(x) = a*(x1^2 - x2)^2 + b*(x1-1)^2 + f0
"""

import numpy as np
import matplotlib.pyplot as plt
import time
from matplotlib.colors import LogNorm
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# 1. Параметры (Вариант 7: a=2, b=2, f0=10, n=2)
# ============================================================
a, b, f0, n = 2, 2, 10, 2

def rosenbrock(x):
    x = np.array(x, dtype=float)
    f = 0
    for i in range(n-1):
        f += a * (x[i]**2 - x[i+1])**2 + b * (x[i] - 1)**2
    return f + f0

def rosenbrock_grad(x):
    x = np.array(x, dtype=float)
    grad = np.zeros(n)
    grad[0] = 2 * a * (x[0]**2 - x[1]) * (2*x[0]) + 2 * b * (x[0] - 1)
    grad[1] = -2 * a * (x[0]**2 - x[1])
    return grad

# ============================================================
# 2. Одномерный поиск
# ============================================================
def golden_section_search(f, a_bound, b_bound, tol=1e-5):
    gr = (np.sqrt(5) - 1) / 2
    a_val, b_val = a_bound, b_bound
    x1 = b_val - gr * (b_val - a_val)
    x2 = a_val + gr * (b_val - a_val)
    f1, f2 = f(x1), f(x2)

    for _ in range(100):
        if abs(b_val - a_val) < tol:
            break
        if f1 < f2:
            b_val, x2, f2 = x2, x1, f1
            x1 = b_val - gr * (b_val - a_val)
            f1 = f(x1)
        else:
            a_val, x1, f1 = x1, x2, f2
            x2 = a_val + gr * (b_val - a_val)
            f2 = f(x2)
    return (a_val + b_val) / 2

def line_search(f, x, d, alpha0=1.0, tol=1e-5):
    def phi(alpha):
        return f(x + alpha * d)

    alpha = alpha0
    while phi(alpha) < phi(alpha/2) and abs(alpha) < 10:
        alpha *= 2
    if alpha > 0:
        a_bound, b_bound = 0, alpha
    else:
        a_bound, b_bound = alpha, 0
    return golden_section_search(phi, a_bound, b_bound, tol)

# ============================================================
# 3. Методы оптимизации
# ============================================================
def dfp_method(f, grad, x0, eps=1e-6, max_iter=200):
    x = np.array(x0, dtype=float)
    G = np.eye(len(x))
    g = grad(x)
    history = [x.copy()]
    grad_norms = [np.linalg.norm(g)]

    for _ in range(max_iter):
        if np.linalg.norm(g) < eps:
            break
        d = -G @ g
        alpha = line_search(f, x, d)
        x_new = x + alpha * d
        g_new = grad(x_new)

        s, y = x_new - x, g_new - g
        sy = np.dot(s, y)
        if sy > 1e-10:
            G = G + np.outer(s, s)/sy - np.outer(G@y, G@y)/(np.dot(y, G@y)+1e-12)

        x, g = x_new, g_new
        history.append(x.copy())
        grad_norms.append(np.linalg.norm(g))

    return x, f(x), history, grad_norms

def bfgs_method(f, grad, x0, eps=1e-6, max_iter=200):
    x = np.array(x0, dtype=float)
    H = np.eye(len(x))
    g = grad(x)
    history = [x.copy()]
    grad_norms = [np.linalg.norm(g)]

    for _ in range(max_iter):
        if np.linalg.norm(g) < eps:
            break
        d = -H @ g
        alpha = line_search(f, x, d)
        x_new = x + alpha * d
        g_new = grad(x_new)

        s, y = x_new - x, g_new - g
        sy = np.dot(s, y)
        if sy > 1e-10:
            rho = 1.0 / sy
            I = np.eye(len(x))
            H = (I - rho*np.outer(s,y)) @ H @ (I - rho*np.outer(y,s)) + rho*np.outer(s,s)

        x, g = x_new, g_new
        history.append(x.copy())
        grad_norms.append(np.linalg.norm(g))

    return x, f(x), history, grad_norms

def fletcher_reeves(f, grad, x0, eps=1e-6, max_iter=200):
    x = np.array(x0, dtype=float)
    g = grad(x)
    d = -g.copy()
    history = [x.copy()]
    grad_norms = [np.linalg.norm(g)]

    for _ in range(max_iter):
        if np.linalg.norm(g) < eps:
            break
        alpha = line_search(f, x, d)
        x_new = x + alpha * d
        g_new = grad(x_new)

        beta = np.dot(g_new, g_new) / (np.dot(g, g) + 1e-12)
        d = -g_new + beta * d

        x, g = x_new, g_new
        history.append(x.copy())
        grad_norms.append(np.linalg.norm(g))

    return x, f(x), history, grad_norms

def polak_ribiere(f, grad, x0, eps=1e-6, max_iter=200):
    x = np.array(x0, dtype=float)
    g = grad(x)
    d = -g.copy()
    history = [x.copy()]
    grad_norms = [np.linalg.norm(g)]

    for _ in range(max_iter):
        if np.linalg.norm(g) < eps:
            break
        alpha = line_search(f, x, d)
        x_new = x + alpha * d
        g_new = grad(x_new)

        beta = np.dot(g_new, g_new - g) / (np.dot(g, g) + 1e-12)
        beta = max(0, beta)
        d = -g_new + beta * d

        x, g = x_new, g_new
        history.append(x.copy())
        grad_norms.append(np.linalg.norm(g))

    return x, f(x), history, grad_norms

# ============================================================
# 4. Визуализация
# ============================================================
def plot_trajectory(f, history, title, x_star):
    history = [np.array(h).flatten() for h in history if len(np.array(h).flatten()) == 2]
    if len(history) < 2:
        return

    x1 = np.linspace(-1.5, 2.5, 200)
    x2 = np.linspace(-0.5, 3, 200)
    X1, X2 = np.meshgrid(x1, x2)
    Z = np.array([[f([x1, x2]) for x1 in x1] for x2 in x2])

    plt.figure(figsize=(10, 8))
    plt.contour(X1, X2, Z, levels=np.logspace(-1, 4, 30), cmap='viridis', norm=LogNorm())
    plt.colorbar(label='f(x)')

    hist = np.array(history)
    plt.plot(hist[:,0], hist[:,1], 'r.-', linewidth=2, markersize=6, label='Траектория')
    plt.plot(hist[0,0], hist[0,1], 'go', markersize=10, label='Старт')
    plt.plot(hist[-1,0], hist[-1,1], 'ro', markersize=10, label='Финиш')
    plt.plot(x_star[0], x_star[1], 'b*', markersize=15, label='Минимум (1,1)')

    plt.xlabel('x₁')
    plt.ylabel('x₂')
    plt.title(title)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

def plot_comparison(methods_data):
    plt.figure(figsize=(14, 5))

    # 左图：梯度收敛
    plt.subplot(1, 2, 1)
    for name, grad_norms in methods_data:
        plt.semilogy(range(len(grad_norms)), grad_norms, 'o-', linewidth=1.5, markersize=4, label=name)
    plt.xlabel('Итерация')
    plt.ylabel('||∇f||')
    plt.title('Сходимость по градиенту')
    plt.legend()
    plt.grid(True, alpha=0.3)

    # 右图：函数值收敛
    plt.subplot(1, 2, 2)
    for name, f_values in methods_data:
        plt.semilogy(range(len(f_values)), f_values, 'o-', linewidth=1.5, markersize=4, label=name)
    plt.xlabel('Итерация')
    plt.ylabel('f(x)')
    plt.title('Сходимость по функции')
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.suptitle('Сравнение методов оптимизации')
    plt.tight_layout()
    plt.show()

# ============================================================
# 5. Основная программа
# ============================================================
def main():
    print("="*70)
    print("ЛАБОРАТОРНАЯ РАБОТА 3 - МЕТОДЫ МНОГОМЕРНОЙ ОПТИМИЗАЦИИ")
    print("Функция Розенброка")
    print("="*70)

    print(f"\nВариант 7: a={a}, b={b}, f0={f0}, n={n}")
    x0 = np.array([-1.2, 1.0])
    x_star = np.array([1.0, 1.0])

    print(f"Начальная точка: {x0}")
    print(f"f(x0) = {rosenbrock(x0):.6f}")
    print(f"\nТочный минимум: x* = {x_star}")
    print(f"f(x*) = {rosenbrock(x_star):.6f}")

    # 分析驻点
    H = np.array([[2*a*(6*1**2 - 2*1) + 2*b, -4*a*1],
                  [-4*a*1, 2*a]])
    eig = np.linalg.eigvals(H)
    print(f"Собственные значения гессиана: {eig[0]:.4f}, {eig[1]:.4f}")
    print("→ x* является локальным минимумом\n")

    # 运行所有方法
    methods = [
        ("DFP", dfp_method),
        ("BFGS", bfgs_method),
        ("Fletcher-Reeves", fletcher_reeves),
        ("Polak-Ribière", polak_ribiere)
    ]

    results = []
    grad_data = []
    func_data = []

    for name, method in methods:
        print(f"\n执行 {name}...")
        start = time.time()
        x_opt, f_opt, hist, grad_norms = method(rosenbrock, rosenbrock_grad, x0)
        elapsed = time.time() - start

        # 计算每次迭代的函数值
        f_values = [rosenbrock(x) for x in hist]

        print(f"  结果: x = ({x_opt[0]:.8f}, {x_opt[1]:.8f})")
        print(f"  f(x) = {f_opt:.8f}")
        print(f"  迭代次数: {len(hist)-1}")
        print(f"  耗时: {elapsed:.6f} 秒")
        print(f"  ||∇f|| = {grad_norms[-1]:.2e}")

        results.append({
            'name': name,
            'iter': len(hist)-1,
            'time': elapsed,
            'grad': grad_norms[-1],
            'f_opt': f_opt
        })

        grad_data.append((name, grad_norms))
        func_data.append((name, f_values))

        # 画轨迹图
        plot_trajectory(rosenbrock, hist, f"Траектория: {name}", x_star)

    # 对比图
    plot_comparison(grad_data)

    # 结果表格
    print("\n" + "="*70)
    print("ИТОГОВАЯ ТАБЛИЦА СРАВНЕНИЯ")
    print("="*70)
    print(f"{'Метод':<20} {'Итерации':<10} {'Время (с)':<12} {'||∇f||':<12} {'f(x*)':<12}")
    print("-"*70)
    for r in results:
        print(f"{r['name']:<20} {r['iter']:<10} {r['time']:<12.6f} {r['grad']:<12.2e} {r['f_opt']:<12.8f}")

    print("\n" + "="*70)
    print("РАБОТА ЗАВЕРШЕНА")
    print("="*70)

if __name__ == "__main__":
    main()